name: Lighthouse CI Audit
on:
  workflow_dispatch:
  workflow_run:
    workflows: ['pages-build-deployment']
    types:
      - completed

jobs:
  lighthouse:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Wait for GitHub Pages to go live
        run: sleep 60
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://cse110-sp25-group13.github.io/dummy_repo/
            https://cse110-sp25-group13.github.io/dummy_repo/expose.html
            https://cse110-sp25-group13.github.io/dummy_repo/explore.html
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
